### ISSUE TITLE
ModuleNotFoundError when running the demo

### ISSUE THREAD

**Issue by kezhen98** [MeshFEM/Inflatables#2]
Hi, I am attempting to reproduce the demo provided in your GitHub repository, and I encountered some errors related to the modules. 

When I run the `ConcentricCricles.ipynb` `Lilium.ipynb` `LogSpiral.ipynb`, I receive the following error message:
ModuleNotFoundError: No module named 'sparse_matrices'

When I run the `ForwardDesign.ipynb`，I receive the following error message:
ModuleNotFoundError: No module named 'wall_generation'

Where can I find these modules? Or did I do something wrong?

Thank you very much!

**Comment by jpanetta** [comment]
These modules are part of the Python bindings built from the Inflatables/MeshFEM C++ codebase. You should make sure the code [built](https://github.com/MeshFEM/Inflatables#obtaining-and-building) without errors and that the Python bindings are being built for the version of Python you're actually using. You'll know you have a version mismatch if these import errors persist despite the build successfully generating compiled modules with paths like `python/wall_generation.cpython-39-darwin.so` (the suffix is platform/version dependent).

The correct Python version should automatically be selected if you're using a virtual environment as recommended in the README. But this is for some reason broken, you can manually override the selection by setting `PYTHON_EXECUTABLE` as documented [here](https://pybind11.readthedocs.io/en/stable/compiling.html#configuration-variables).

**Comment by kezhen98** [comment]
It works now! Thank you!
